name: build and test

on:
  push:
    branches:
      - main
    paths:
      - server/**
      - .github/workflows/main_dealfortressapi.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Build with dotnet
        run: dotnet build server --configuration Release
      - name: Test
        run: dotnet test server.sln --no-restore --verbosity normal
